[dotfiles]
"topgrade/topgrade.toml" = { source = "dotfiles/topgrade/topgrade.toml", mode = "copy", variants = [
  { os = "linux", target = "~/.config/topgrade/topgrade.toml" },
  { os = "windows", target = "~/AppData/Roaming/topgrade/topgrade.toml" },
] }
"powershell/init.ps1" = { source = "dotfiles/powershell/init.ps1", mode = "copy", variants = [
  { os = "linux", target = "~/.config/powershell/init.ps1" },
  { os = "windows", target = "~/Documents/Powershell/init.ps1" },
] }
"powershell/Microsoft.PowerShell_profile.ps1" = { source = "dotfiles/powershell/Microsoft.PowerShell_profile.ps1", mode = "copy", variants = [
  { os = "linux", target = "~/.config/powershell/Microsoft.PowerShell_profile.ps1" },
  { os = "windows", target = "~/Documents/Powershell/Microsoft.PowerShell_profile.ps1" },
] }

[tools]
powershell = "7.6.6"
zoxide = "0.10.0"
